apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-arts-app
spec:
  selector:
    matchLabels:
      app: e-arts-app
  replicas: 3
  template:
    metadata:
      labels:
        app: e-arts-app
    spec:
      containers:
        - name: e-arts-app
          image: ""
          ports:
            - containerPort: 3000
